version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
  api:
    image: hiimtmac/swift-bug
    container_name: api
    command: ['serve', '--env', 'development', '--hostname', '0.0.0.0', '--port', '8080']
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - db
